import pytest

from senri_ffi.types.library_like import is_library_like, get_missing_methods, MANDATORY_METHODS


class TestIsLibraryLike:
    def test_valid_object(self):
        class ValidBackend:
            def open(self, path): ...
            def bind(self, handle, name, ret, args): ...
            def close(self, handle): ...
            def alloc(self, size): ...
            def free(self, ptr): ...
            def address_of(self, buffer): ...
            def register_callback(self, func, ret, args): ...
            def unregister_callback(self, ptr): ...
            def get_errno(self): ...
            def get_strerror(self, errno): ...

        assert is_library_like(ValidBackend())

    def test_missing_method(self):
        class Incomplete:
            def open(self, path): ...
            def bind(self, handle, name, ret, args): ...

        assert not is_library_like(Incomplete())

    def test_none(self):
        assert not is_library_like(None)


class TestGetMissingMethods:
    def test_all_missing_on_none(self):
        missing = get_missing_methods(None)
        assert len(missing) == len(MANDATORY_METHODS)

    def test_no_missing_on_complete(self):
        class Complete:
            def open(self, path): ...
            def bind(self, handle, name, ret, args): ...
            def close(self, handle): ...
            def alloc(self, size): ...
            def free(self, ptr): ...
            def address_of(self, buffer): ...
            def register_callback(self, func, ret, args): ...
            def unregister_callback(self, ptr): ...
            def get_errno(self): ...
            def get_strerror(self, errno): ...

        assert get_missing_methods(Complete()) == []

    def test_partial_missing(self):
        class Partial:
            def open(self, path): ...
            def alloc(self, size): ...

        missing = get_missing_methods(Partial())
        assert "open" not in missing
        assert "alloc" not in missing
        assert "bind" in missing
        assert "close" in missing
